name: accessibility_lint
description: A custom lint rule for accessibility.
version: 0.0.1
repository: https://github.com/MateuxLucax/accessibility-lint
issue_tracker: https://github.com/MateuxLucax/accessibility-lint/issues

environment:
  sdk: ^3.5.0

dependencies:
  analyzer: ^6.7.0
  custom_lint_builder: ^0.6.5
  analyzer_plugin: ^0.11.3

dev_dependencies:
  lints: ^4.0.0
