name: accessibility_lint
description: A custom lint rule for accessibility.
version: 1.0.0

environment:
  sdk: ^3.5.0

dependencies:
  analyzer: ^6.7.0
  custom_lint_builder: ^0.6.5

dev_dependencies:
  lints: ^4.0.0
